// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace GalaxyCloud.Feature
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Samsung Cloud Sync Settings")]
    [NUnit.Framework.CategoryAttribute("NCGP-1078")]
    public partial class SamsungCloudSyncSettingsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "NCGP-1078"};
        
#line 1 "SamsungCloudSyncSettings.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Feature", "Samsung Cloud Sync Settings", "\tAs a Samsung Account App user,\r\n\tI want to get access to the application list wh" +
                    "ich supports Samsung Cloud Sync feature\r\n\tso that I can change my settings and s" +
                    "tart synchronization for each application.", ProgrammingLanguage.CSharp, new string[] {
                        "NCGP-1078"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
#line hidden
#line 8
 testRunner.Given("\"Samsung Cloud\" app is launched", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 9
 testRunner.And("Samsung Cloud app list is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Validate network configuration (Wifi only or Wifi + mobile)")]
        [NUnit.Framework.CategoryAttribute("NCPG-T351")]
        [NUnit.Framework.TestCaseAttribute("Samsung Gallery", "Wi-Fi and Ethernet only", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Gallery", "Wi-Fi, Ethernet, and mobile data", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Notes", "Wi-Fi and Ethernet only", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Notes", "Wi-Fi, Ethernet, and mobile data", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Pass", "Wi-Fi and Ethernet only", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Pass", "Wi-Fi, Ethernet, and mobile data", null)]
        public virtual void ValidateNetworkConfigurationWifiOnlyOrWifiMobile(string appsName, string radio, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "NCPG-T351"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("appsName", appsName);
            argumentsOfScenario.Add("radio", radio);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validate network configuration (Wifi only or Wifi + mobile)", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 12
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 13
 testRunner.Given(string.Format("the \"{0}\" app settings is accessed", appsName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 14
 testRunner.And("the sync status is changed to \"ON\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 15
 testRunner.Then(string.Format("the \"{0}\" radio button selection in the application on the Samsung Cloud is chang" +
                            "ed", radio), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that with toggle button on OFF is not possible to sync")]
        [NUnit.Framework.CategoryAttribute("NCGP-T413")]
        [NUnit.Framework.CategoryAttribute("NCGP-297")]
        [NUnit.Framework.CategoryAttribute("NCGP-301")]
        [NUnit.Framework.TestCaseAttribute("Bluetooth", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Gallery", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Notes", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Pass", null)]
        [NUnit.Framework.TestCaseAttribute("Wi-Fi", null)]
        public virtual void VerifyThatWithToggleButtonOnOFFIsNotPossibleToSync(string appsName, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "NCGP-T413",
                    "NCGP-297",
                    "NCGP-301"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("appsName", appsName);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that with toggle button on OFF is not possible to sync", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 27
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 28
 testRunner.Given(string.Format("the \"{0}\" app settings is accessed", appsName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 29
 testRunner.When("the toggle button status is \"OFF\" on app settings", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 30
 testRunner.Then("sync now button should be disabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that the submenu App Settings can be opened")]
        [NUnit.Framework.CategoryAttribute("NCGP-T423")]
        [NUnit.Framework.TestCaseAttribute("Bluetooth", "Bluetooth sync", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Gallery", "Gallery sync with OneDrive", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Notes", "Samsung Notes sync", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Pass", "Samsung Pass sync", null)]
        [NUnit.Framework.TestCaseAttribute("Wi-Fi", "Wi-Fi sync", null)]
        public virtual void VerifyThatTheSubmenuAppSettingsCanBeOpened(string appsName, string titleName, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "NCGP-T423"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("appsName", appsName);
            argumentsOfScenario.Add("titleName", titleName);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that the submenu App Settings can be opened", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 41
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 42
 testRunner.When(string.Format("the \"{0}\" app settings is accessed", appsName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 43
 testRunner.Then(string.Format("should be can opened the \"{0}\" app settings page", titleName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify if the app toggle button at the dashboard page is off, the \"Sync now\" butt" +
            "on is disabled in the app settings")]
        [NUnit.Framework.CategoryAttribute("NCGP-T424")]
        [NUnit.Framework.CategoryAttribute("NCGP-297")]
        [NUnit.Framework.CategoryAttribute("NCGP-301")]
        [NUnit.Framework.TestCaseAttribute("Bluetooth", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Gallery", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Notes", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Pass", null)]
        [NUnit.Framework.TestCaseAttribute("Wi-Fi", null)]
        public virtual void VerifyIfTheAppToggleButtonAtTheDashboardPageIsOffTheSyncNowButtonIsDisabledInTheAppSettings(string appsName, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "NCGP-T424",
                    "NCGP-297",
                    "NCGP-301"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("appsName", appsName);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify if the app toggle button at the dashboard page is off, the \"Sync now\" butt" +
                    "on is disabled in the app settings", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 54
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 55
 testRunner.When(string.Format("the \"{0}\" toggle button status is \"OFF\"", appsName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 56
 testRunner.And(string.Format("the \"{0}\" app settings is accessed", appsName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 57
 testRunner.Then("sync now button should be disabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that \"Last Sync\" info is displayed at Cloud settings page")]
        [NUnit.Framework.CategoryAttribute("NCGP-T545")]
        [NUnit.Framework.TestCaseAttribute("Bluetooth", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Notes", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Pass", null)]
        [NUnit.Framework.TestCaseAttribute("Wi-Fi", null)]
        public virtual void VerifyThatLastSyncInfoIsDisplayedAtCloudSettingsPage(string appsName, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "NCGP-T545"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("appsName", appsName);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that \"Last Sync\" info is displayed at Cloud settings page", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 68
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 69
 testRunner.Given(string.Format("the \"{0}\" app settings is accessed", appsName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 70
 testRunner.Then("last Sync info should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that \"Last Sync\" displays the right date and time at Cloud settings page")]
        [NUnit.Framework.CategoryAttribute("NCGP-T546")]
        [NUnit.Framework.TestCaseAttribute("Bluetooth", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Gallery", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Notes", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Pass", null)]
        [NUnit.Framework.TestCaseAttribute("Wi-Fi", null)]
        public virtual void VerifyThatLastSyncDisplaysTheRightDateAndTimeAtCloudSettingsPage(string appsName, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "NCGP-T546"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("appsName", appsName);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that \"Last Sync\" displays the right date and time at Cloud settings page", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 80
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 81
 testRunner.Given(string.Format("the \"{0}\" app settings is accessed", appsName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 82
 testRunner.When("the sync ocurrs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 83
 testRunner.Then("sync info for date and time should be updated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that the \"Sync using\" selection persists when switching between screens")]
        [NUnit.Framework.CategoryAttribute("NCGP-T592")]
        [NUnit.Framework.TestCaseAttribute("Bluetooth", "Wi-Fi and Ethernet only", null)]
        [NUnit.Framework.TestCaseAttribute("Bluetooth", "Wi-Fi, Ethernet, and mobile data", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Gallery", "Wi-Fi and Ethernet only", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Gallery", "Wi-Fi, Ethernet, and mobile data", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Notes", "Wi-Fi and Ethernet only", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Notes", "Wi-Fi, Ethernet, and mobile data", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Pass", "Wi-Fi and Ethernet only", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Pass", "Wi-Fi, Ethernet, and mobile data", null)]
        [NUnit.Framework.TestCaseAttribute("Wi-Fi", "Wi-Fi and Ethernet only", null)]
        [NUnit.Framework.TestCaseAttribute("Wi-Fi", "Wi-Fi, Ethernet, and mobile data", null)]
        public virtual void VerifyThatTheSyncUsingSelectionPersistsWhenSwitchingBetweenScreens(string appsName, string radioSelection, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "NCGP-T592"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("appsName", appsName);
            argumentsOfScenario.Add("radioSelection", radioSelection);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that the \"Sync using\" selection persists when switching between screens", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 94
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 95
 testRunner.Given(string.Format("the \"{0}\" app settings is accessed", appsName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 96
 testRunner.And("the sync status is changed to \"ON\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 97
 testRunner.When(string.Format("the \"{0}\" radio button selection in the application on the Samsung Cloud is chang" +
                            "ed", radioSelection), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 98
 testRunner.And(string.Format("switch between the Dashboard and the \"{0}\" app settings screen", appsName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 99
 testRunner.Then(string.Format("the radio button \"{0}\" in the app settings screen must remain selected", radioSelection), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that the more information page is displayed")]
        [NUnit.Framework.CategoryAttribute("NCGP-T637")]
        [NUnit.Framework.TestCaseAttribute("Bluetooth", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Notes", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Pass", null)]
        [NUnit.Framework.TestCaseAttribute("Wi-Fi", null)]
        public virtual void VerifyThatTheMoreInformationPageIsDisplayed(string appsName, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "NCGP-T637"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("appsName", appsName);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that the more information page is displayed", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 115
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 116
 testRunner.Given(string.Format("the \"{0}\" app settings is accessed", appsName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 117
 testRunner.When("the more information menu is accessed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 118
 testRunner.Then("the \"More information\" page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that the more information pop-up menu is displayed on Samsung Notes and Sa" +
            "msung Settings")]
        [NUnit.Framework.CategoryAttribute("NCGP-T638")]
        [NUnit.Framework.TestCaseAttribute("Bluetooth", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Notes", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Pass", null)]
        [NUnit.Framework.TestCaseAttribute("Wi-Fi", null)]
        public virtual void VerifyThatTheMoreInformationPop_UpMenuIsDisplayedOnSamsungNotesAndSamsungSettings(string appsName, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "NCGP-T638"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("appsName", appsName);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that the more information pop-up menu is displayed on Samsung Notes and Sa" +
                    "msung Settings", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 128
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 129
 testRunner.Given(string.Format("the \"{0}\" app settings is accessed", appsName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 130
 testRunner.When("the more option menu is clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 131
 testRunner.Then("the popup button is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that the more information menu icon is enabled")]
        [NUnit.Framework.CategoryAttribute("NCGP-T639")]
        [NUnit.Framework.TestCaseAttribute("Bluetooth", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Notes", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Pass", null)]
        [NUnit.Framework.TestCaseAttribute("Wi-Fi", null)]
        public virtual void VerifyThatTheMoreInformationMenuIconIsEnabled(string appsName, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "NCGP-T639"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("appsName", appsName);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that the more information menu icon is enabled", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 141
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 142
 testRunner.Given(string.Format("the \"{0}\" app settings is accessed", appsName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 143
 testRunner.Then("the more information menu icon is enabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that the more information menu icon is not displayed on Samsung Gallery")]
        [NUnit.Framework.CategoryAttribute("NCGP-642")]
        [NUnit.Framework.TestCaseAttribute("Samsung Gallery", null)]
        public virtual void VerifyThatTheMoreInformationMenuIconIsNotDisplayedOnSamsungGallery(string appsName, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "NCGP-642"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("appsName", appsName);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that the more information menu icon is not displayed on Samsung Gallery", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 153
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 154
 testRunner.Given(string.Format("the \"{0}\" app settings is accessed", appsName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 155
 testRunner.Then("the more information menu icon should not be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Validate cancel sync")]
        [NUnit.Framework.CategoryAttribute("NCGP-T366")]
        [NUnit.Framework.TestCaseAttribute("Bluetooth", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Gallery", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Notes", null)]
        [NUnit.Framework.TestCaseAttribute("Samsung Pass", null)]
        [NUnit.Framework.TestCaseAttribute("Wi-Fi", null)]
        public virtual void ValidateCancelSync(string appsName, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "NCGP-T366"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("appsName", appsName);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validate cancel sync", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 162
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 163
 testRunner.Given(string.Format("the \"{0}\" app settings is accessed", appsName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 164
 testRunner.And("the sync status is changed to \"ON\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 165
 testRunner.And("get last synchronization date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 166
 testRunner.When("the user start/stop synchronization", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 167
 testRunner.Then("the synchronization date has not changed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
