// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace GalaxyCloud.Feature
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Two Way Communication")]
    [NUnit.Framework.CategoryAttribute("NCGP-1103")]
    public partial class TwoWayCommunicationFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "NCGP-1103"};
        
#line 1 "TwoWayCommunication.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Feature", "Two Way Communication", "\tAs a user of the Samsung Account app, \r\n\tI want the data of the sync is automati" +
                    "cally updated \r\n\twhen the Gallery changes", ProgrammingLanguage.CSharp, new string[] {
                        "NCGP-1103"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
#line hidden
#line 8
 testRunner.Given("\"Samsung Cloud\" app is launched", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 9
 testRunner.And("Samsung Cloud app list is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that when toggle button is changed on the Samsung Gallery application it r" +
            "eflects at Samsung Cloud APP")]
        [NUnit.Framework.CategoryAttribute("NCGP-T427")]
        [NUnit.Framework.CategoryAttribute("Gallery")]
        [NUnit.Framework.TestCaseAttribute("ON", null)]
        [NUnit.Framework.TestCaseAttribute("OFF", null)]
        public virtual void VerifyThatWhenToggleButtonIsChangedOnTheSamsungGalleryApplicationItReflectsAtSamsungCloudAPP(string status, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "NCGP-T427",
                    "Gallery"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Status", status);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that when toggle button is changed on the Samsung Gallery application it r" +
                    "eflects at Samsung Cloud APP", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 12
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 13
 testRunner.Given("the \"Samsung Gallery\" app is opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 14
 testRunner.When("the toggle button status is changed on Gallery app to \"<status>\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 15
 testRunner.Then("the related toggle button \"Samsung Gallery\" status in the Samsung Cloud must be u" +
                        "pdated to \"<status>\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that when the Sync Using radio button selection is changed in the applicat" +
            "ion, the related toggle button status in the Samsung Cloud is updated")]
        [NUnit.Framework.CategoryAttribute("NCGP-T508")]
        [NUnit.Framework.CategoryAttribute("Gallery")]
        [NUnit.Framework.TestCaseAttribute("Wi-Fi and Ethernet only", null)]
        [NUnit.Framework.TestCaseAttribute("Wi-Fi, Ethernet, and mobile data", null)]
        public virtual void VerifyThatWhenTheSyncUsingRadioButtonSelectionIsChangedInTheApplicationTheRelatedToggleButtonStatusInTheSamsungCloudIsUpdated(string status, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "NCGP-T508",
                    "Gallery"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("status", status);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that when the Sync Using radio button selection is changed in the applicat" +
                    "ion, the related toggle button status in the Samsung Cloud is updated", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 23
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 24
 testRunner.Given("the \"Samsung Gallery\" app is opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 25
 testRunner.And(string.Format("the Sync Using \'{0}\' radio button selection is changed in the Gallery application" +
                            "", status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 26
 testRunner.And("the \"Samsung Gallery\" settings screen is accessed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 27
 testRunner.Then(string.Format("the related radio button \"{0}\" selection in the Samsung Cloud should be updated", status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that when the Sync Using radio button selection is changed in the Samsung " +
            "Cloud, the related radio button selection in the Samsung Gallery app is updated")]
        [NUnit.Framework.CategoryAttribute("NCGP-T509")]
        [NUnit.Framework.CategoryAttribute("NCGP-1210")]
        [NUnit.Framework.CategoryAttribute("Gallery")]
        [NUnit.Framework.TestCaseAttribute("Wi-Fi and Ethernet only", null)]
        [NUnit.Framework.TestCaseAttribute("Wi-Fi, Ethernet, and mobile data", null)]
        public virtual void VerifyThatWhenTheSyncUsingRadioButtonSelectionIsChangedInTheSamsungCloudTheRelatedRadioButtonSelectionInTheSamsungGalleryAppIsUpdated(string status, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "NCGP-T509",
                    "NCGP-1210",
                    "Gallery"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("status", status);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that when the Sync Using radio button selection is changed in the Samsung " +
                    "Cloud, the related radio button selection in the Samsung Gallery app is updated", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 35
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 36
 testRunner.When("the \"Samsung Gallery\" settings screen is accessed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 37
 testRunner.And("the sync status is changed to \"ON\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 38
 testRunner.And(string.Format("the \"{0}\" radio button selection in the application on the Samsung Cloud is chang" +
                            "ed", status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 39
 testRunner.Then("the \"Samsung Gallery\" app is opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 40
 testRunner.And(string.Format("the \"Samsung Gallery\" application is updated for the same \"{0}\" selection", status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that when the Sync Using radio button selection is changed in the Samsung " +
            "Cloud, the related radio button selection in the Samsung Pass app is updated")]
        [NUnit.Framework.CategoryAttribute("NCGP-T509")]
        [NUnit.Framework.CategoryAttribute("NCGP-1210")]
        [NUnit.Framework.CategoryAttribute("Pass")]
        [NUnit.Framework.TestCaseAttribute("Wi-Fi and Ethernet only", null)]
        [NUnit.Framework.TestCaseAttribute("Wi-Fi, Ethernet, and mobile data", null)]
        public virtual void VerifyThatWhenTheSyncUsingRadioButtonSelectionIsChangedInTheSamsungCloudTheRelatedRadioButtonSelectionInTheSamsungPassAppIsUpdated(string status, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "NCGP-T509",
                    "NCGP-1210",
                    "Pass"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("status", status);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that when the Sync Using radio button selection is changed in the Samsung " +
                    "Cloud, the related radio button selection in the Samsung Pass app is updated", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 48
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 49
 testRunner.When("the \"Samsung Pass\" settings screen is accessed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 50
 testRunner.And("the sync status is changed to \"ON\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 51
 testRunner.And(string.Format("the \"{0}\" radio button selection in the application on the Samsung Cloud is chang" +
                            "ed", status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 52
 testRunner.Then("the \"Samsung Pass\" app is opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 53
 testRunner.And(string.Format("the \"Samsung Pass\" application is updated for the same \"{0}\" selection", status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that when toggle button is changed on the Samsung Notes APP it reflects at" +
            " Samsung Cloud APP")]
        [NUnit.Framework.CategoryAttribute("NCGP-T510")]
        [NUnit.Framework.CategoryAttribute("Notes")]
        [NUnit.Framework.TestCaseAttribute("OFF", null)]
        [NUnit.Framework.TestCaseAttribute("ON", null)]
        public virtual void VerifyThatWhenToggleButtonIsChangedOnTheSamsungNotesAPPItReflectsAtSamsungCloudAPP(string status, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "NCGP-T510",
                    "Notes"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("status", status);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that when toggle button is changed on the Samsung Notes APP it reflects at" +
                    " Samsung Cloud APP", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 61
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 62
 testRunner.Given("the \"Samsung Notes\" app is opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 63
 testRunner.When(string.Format("the toggle button status is changed on Samsung Notes app to \"{0}\"", status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 64
 testRunner.Then(string.Format("the related toggle button \"Samsung Notes\" status in the Samsung Cloud must be upd" +
                            "ated to \"{0}\"", status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that when toggle button is changed on the Samsung Cloud APP it reflects at" +
            " gallery APP")]
        [NUnit.Framework.CategoryAttribute("NCGP-T428")]
        [NUnit.Framework.CategoryAttribute("Gallery")]
        [NUnit.Framework.TestCaseAttribute("ON", null)]
        [NUnit.Framework.TestCaseAttribute("OFF", null)]
        public virtual void VerifyThatWhenToggleButtonIsChangedOnTheSamsungCloudAPPItReflectsAtGalleryAPP(string status, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "NCGP-T428",
                    "Gallery"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("status", status);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that when toggle button is changed on the Samsung Cloud APP it reflects at" +
                    " gallery APP", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 72
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 73
 testRunner.When(string.Format("the toggle button status of \"Samsung Gallery\" is changed on Cloud app to \"{0}\"", status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 74
 testRunner.And("the \"Samsung Gallery\" app is opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 75
 testRunner.Then(string.Format("the status of the related toggle button in the Gallery app should be updated to \"" +
                            "{0}\"", status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that when toggle button is changed on the Samsung Cloud APP it reflects at" +
            " Samsung Notes APP")]
        [NUnit.Framework.CategoryAttribute("NCGP-T530")]
        [NUnit.Framework.CategoryAttribute("Notes")]
        [NUnit.Framework.TestCaseAttribute("OFF", null)]
        [NUnit.Framework.TestCaseAttribute("ON", null)]
        public virtual void VerifyThatWhenToggleButtonIsChangedOnTheSamsungCloudAPPItReflectsAtSamsungNotesAPP(string status, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "NCGP-T530",
                    "Notes"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("status", status);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that when toggle button is changed on the Samsung Cloud APP it reflects at" +
                    " Samsung Notes APP", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 83
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 84
 testRunner.Given("the \"Samsung Notes\" app is opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 85
 testRunner.When(string.Format("the toggle button status of \"Samsung Notes\" is changed on Cloud app to \"{0}\"", status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 86
 testRunner.Then(string.Format("the status of the related toggle button in the Notes app should be updated to \"{0" +
                            "}\"", status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that when the \"Sync Now\" button in the Samsung Cloud is clicked, the \"Last" +
            " refreshed on\"/\"Last synced\" information is updated in the Samsung Gallery appli" +
            "cation")]
        [NUnit.Framework.CategoryAttribute("NCGP-T430")]
        [NUnit.Framework.CategoryAttribute("Gallery")]
        public virtual void VerifyThatWhenTheSyncNowButtonInTheSamsungCloudIsClickedTheLastRefreshedOnLastSyncedInformationIsUpdatedInTheSamsungGalleryApplication()
        {
            string[] tagsOfScenario = new string[] {
                    "NCGP-T430",
                    "Gallery"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that when the \"Sync Now\" button in the Samsung Cloud is clicked, the \"Last" +
                    " refreshed on\"/\"Last synced\" information is updated in the Samsung Gallery appli" +
                    "cation", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 94
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 95
 testRunner.Given("the \"Samsung Gallery\" app settings is accessed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 96
 testRunner.When("the sync ocurrs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 97
 testRunner.Given("the \"Samsung Gallery\" app is opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 98
 testRunner.Then("the information of Last Synced \"Samsung Gallery\" and Sync info are updated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that when the \"Sync Now\" button in the Samsung Cloud is clicked, the \"Last" +
            " refreshed on\"/\"Last synced\" information is updated in the related Samsung Notes" +
            " application")]
        [NUnit.Framework.CategoryAttribute("NCGP-T430")]
        [NUnit.Framework.CategoryAttribute("Notes")]
        public virtual void VerifyThatWhenTheSyncNowButtonInTheSamsungCloudIsClickedTheLastRefreshedOnLastSyncedInformationIsUpdatedInTheRelatedSamsungNotesApplication()
        {
            string[] tagsOfScenario = new string[] {
                    "NCGP-T430",
                    "Notes"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that when the \"Sync Now\" button in the Samsung Cloud is clicked, the \"Last" +
                    " refreshed on\"/\"Last synced\" information is updated in the related Samsung Notes" +
                    " application", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 101
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 102
 testRunner.Given("the \"Samsung Notes\" app settings is accessed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 103
 testRunner.When("the sync ocurrs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 104
 testRunner.Given("the \"Samsung Notes\" app is opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 105
 testRunner.Then("the information of Last Synced \"Samsung Notes\" and Sync info are updated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that when the \"Sync Now\" button in the Samsung Cloud is clicked, the \"Last" +
            " refreshed on\"/\"Last synced\" information is updated in the Samsung Pass applicat" +
            "ion")]
        [NUnit.Framework.CategoryAttribute("NCGP-T430")]
        [NUnit.Framework.CategoryAttribute("Pass")]
        public virtual void VerifyThatWhenTheSyncNowButtonInTheSamsungCloudIsClickedTheLastRefreshedOnLastSyncedInformationIsUpdatedInTheSamsungPassApplication()
        {
            string[] tagsOfScenario = new string[] {
                    "NCGP-T430",
                    "Pass"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that when the \"Sync Now\" button in the Samsung Cloud is clicked, the \"Last" +
                    " refreshed on\"/\"Last synced\" information is updated in the Samsung Pass applicat" +
                    "ion", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 108
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 109
 testRunner.Given("the \"Samsung Pass\" app settings is accessed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 110
 testRunner.When("the sync ocurrs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 111
 testRunner.Given("the \"Samsung Pass\" app is opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 112
 testRunner.Then("the information of Last Synced \"Samsung Pass\" and Sync info are updated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that when the toggle button is changed in the Samsung Cloud, sync selectio" +
            "n in  Samsung Gallerythe application is updated")]
        [NUnit.Framework.CategoryAttribute("NCGP-T295")]
        [NUnit.Framework.CategoryAttribute("Gallery")]
        [NUnit.Framework.TestCaseAttribute("OFF", null)]
        [NUnit.Framework.TestCaseAttribute("ON", null)]
        public virtual void VerifyThatWhenTheToggleButtonIsChangedInTheSamsungCloudSyncSelectionInSamsungGallerytheApplicationIsUpdated(string status, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "NCGP-T295",
                    "Gallery"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("status", status);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that when the toggle button is changed in the Samsung Cloud, sync selectio" +
                    "n in  Samsung Gallerythe application is updated", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 115
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 116
 testRunner.Given(string.Format("the toggle button status of \"Samsung Gallery\" is changed on Cloud app to \"{0}\"", status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 117
 testRunner.When("the \"Samsung Gallery\" app is opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 118
 testRunner.Then(string.Format("the status of the related toggle button in the \"Samsung Gallery\" app should be up" +
                            "dated to \"{0}\"", status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that when the toggle button is changed in the Samsung Cloud, sync selectio" +
            "n in the Samsung Notes application is updated")]
        [NUnit.Framework.CategoryAttribute("NCGP-T295")]
        [NUnit.Framework.CategoryAttribute("Notes")]
        [NUnit.Framework.TestCaseAttribute("OFF", null)]
        [NUnit.Framework.TestCaseAttribute("ON", null)]
        public virtual void VerifyThatWhenTheToggleButtonIsChangedInTheSamsungCloudSyncSelectionInTheSamsungNotesApplicationIsUpdated(string status, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "NCGP-T295",
                    "Notes"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("status", status);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that when the toggle button is changed in the Samsung Cloud, sync selectio" +
                    "n in the Samsung Notes application is updated", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 126
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 127
 testRunner.Given(string.Format("the toggle button status of \"Samsung Notes\" is changed on Cloud app to \"{0}\"", status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 128
 testRunner.When("the \"Samsung Notes\" app is opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 129
 testRunner.Then(string.Format("the status of the related toggle button in the \"Samsung Notes\" app should be upda" +
                            "ted to \"{0}\"", status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that when the toggle button status is changed in the Samsung Pass, the rel" +
            "ated toggle button status in the Samsung Cloud is updated")]
        [NUnit.Framework.CategoryAttribute("NCGP-T1205")]
        [NUnit.Framework.CategoryAttribute("Pass")]
        [NUnit.Framework.TestCaseAttribute("OFF", null)]
        [NUnit.Framework.TestCaseAttribute("ON", null)]
        public virtual void VerifyThatWhenTheToggleButtonStatusIsChangedInTheSamsungPassTheRelatedToggleButtonStatusInTheSamsungCloudIsUpdated(string status, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "NCGP-T1205",
                    "Pass"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("status", status);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that when the toggle button status is changed in the Samsung Pass, the rel" +
                    "ated toggle button status in the Samsung Cloud is updated", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 137
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 138
 testRunner.Given("the \"Samsung Pass\" app is opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 139
 testRunner.When(string.Format("the toggle button status is changed on Samsung Pass app to \"{0}\"", status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 140
 testRunner.Then(string.Format("the related toggle button \"Samsung Pass\" status in the Samsung Cloud must be upda" +
                            "ted to \"{0}\"", status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that when toggle button is changed on the Samsung Cloud app it reflects at" +
            " Samsung Pass app")]
        [NUnit.Framework.CategoryAttribute("NCGP-T1206")]
        [NUnit.Framework.CategoryAttribute("Pass")]
        [NUnit.Framework.TestCaseAttribute("OFF", null)]
        [NUnit.Framework.TestCaseAttribute("ON", null)]
        public virtual void VerifyThatWhenToggleButtonIsChangedOnTheSamsungCloudAppItReflectsAtSamsungPassApp(string status, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "NCGP-T1206",
                    "Pass"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("status", status);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that when toggle button is changed on the Samsung Cloud app it reflects at" +
                    " Samsung Pass app", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 148
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 149
 testRunner.Given("the \"Samsung Pass\" app is opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 150
 testRunner.When(string.Format("the toggle button status of \"Samsung Pass\" is changed on Cloud app to \"{0}\"", status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 151
 testRunner.Then(string.Format("the status of the related toggle button in the Samsung Pass application should be" +
                            " updated to \"{0}\"", status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that when the Sync now button is clicked in the Samsung Pass Application, " +
            "the information of \"Last Synced\" and \"Sync info\" are updated in the related app " +
            "in Samsung Cloud")]
        [NUnit.Framework.CategoryAttribute("NCGP-T1208")]
        [NUnit.Framework.CategoryAttribute("Pass")]
        public virtual void VerifyThatWhenTheSyncNowButtonIsClickedInTheSamsungPassApplicationTheInformationOfLastSyncedAndSyncInfoAreUpdatedInTheRelatedAppInSamsungCloud()
        {
            string[] tagsOfScenario = new string[] {
                    "NCGP-T1208",
                    "Pass"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that when the Sync now button is clicked in the Samsung Pass Application, " +
                    "the information of \"Last Synced\" and \"Sync info\" are updated in the related app " +
                    "in Samsung Cloud", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 159
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 160
 testRunner.Given("the \"Samsung Pass\" app is opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 161
 testRunner.When("the \"Samsung Pass\" sync now is runs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 162
 testRunner.And("the \"Samsung Pass\" app settings is accessed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 163
 testRunner.Then("the \"Samsung Pass\" information of Last Synced and Sync info are updated in the Sa" +
                        "msung Cloud", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Verify that when the Sync Using radio button selection is changed on the Samsung " +
            "Pass, the related toggle button status in the Samsung Cloud is updated")]
        [NUnit.Framework.CategoryAttribute("NCGP-T1209")]
        [NUnit.Framework.CategoryAttribute("Pass")]
        [NUnit.Framework.TestCaseAttribute("Wi-Fi and Ethernet only", null)]
        [NUnit.Framework.TestCaseAttribute("Wi-Fi, Ethernet, and mobile data", null)]
        public virtual void VerifyThatWhenTheSyncUsingRadioButtonSelectionIsChangedOnTheSamsungPassTheRelatedToggleButtonStatusInTheSamsungCloudIsUpdated(string status, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "NCGP-T1209",
                    "Pass"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("status", status);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify that when the Sync Using radio button selection is changed on the Samsung " +
                    "Pass, the related toggle button status in the Samsung Cloud is updated", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 166
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
this.FeatureBackground();
#line hidden
#line 167
 testRunner.Given("the \"Samsung Pass\" app is opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 168
 testRunner.When(string.Format("the sync using \"{0}\" radio button selection is changed on the Samsung Pass applic" +
                            "ation", status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 169
 testRunner.Then("the \"Samsung Pass\" app settings is accessed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 170
 testRunner.And(string.Format("the related radio button \"{0}\" selection in the Samsung Cloud should be updated", status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
